apiVersion: v1
kind: Service
metadata:
  name: web-server-service
spec:
  type: ClusterIP
  ports:
    - port: 8085
      targetPort: 8085
      protocol: TCP
      name: http
  selector:
    app: web-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server

spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      name: web-server
      labels:
        app: web-server
        task: final
    spec:
      containers:
        - image: quay.io/myafk/interactive:stable
          name: web-server
          command: ["interactive", "ingress"]
          env:
            - name: REDIS_SLAVE_HOST
              valueFrom:
                configMapKeyRef:
                  name: werserveerconfig
                  key: REDIS_SLAVE_HOST
            - name: REDIS_MASTER_HOST
              valueFrom:
                configMapKeyRef:
                  name: werserveerconfig
                  key: REDIS_MASTER_HOST
            - name: KUBERNETES_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: werserveerconfig
                  key: KUBERNETES_SERVICE_HOST
            - name: KUBERNETES_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: werserveerconfig
                  key: KUBERNETES_SERVICE_PORT
            - name: ELASTICSEARCH_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: werserveerconfig
                  key: ELASTICSEARCH_HOSTS
          ports:
            - containerPort: 8085