# ConfigMap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: es-common
data:
  discovery.seed_hosts: "elasticsearch-0.elasticsearch,elasticsearch-1.elasticsearch"
  cluster.name: "docker-cluster"
  bootstrap.memory_lock: "false"
  cluster.initial_master_nodes: "elasticsearch-0,elasticsearch-1"
# ClusterIP Service elasticsearch-0
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  type: ClusterIP
  ports:
    - port: 9200
      name: rest
    - port: 9300
      name: inter-node
  selector:
    app: elasticsearch
# StatefulSet elasticsearch
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch

spec:
  replicas: 2
  serviceName: elasticsearch
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      name: elasticsearch
      labels:
        app: elasticsearch
        task: final
        es: cluster
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
#          env:
#            - name: node.name
#                valueFrom:
#                  fieldRef:
#                    fieldPath: metadata.name
          envFrom:
            - configMapRef:
                name: es-common
          ports:
            - containerPort: 9200
              name: rest
              protocol: TCP

            - containerPort: 9300
              name: inter-node
              protocol: TCP

