apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-server
spec:
  rules:
    - host: myapp.example.com
      http:
        paths:
          - path: /webserver
            backend:
              serviceName: web-server-service
              servicePort: 80
          - path: /es
            backend:
              serviceName: elasticsearch
              servicePort: 9200
          - path: /kibana
            backend:
              serviceName: kibana
              servicePort: 5601