apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-0
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    server: 192.168.123.254
    path: "/home/nfsshare/elasticsearch-0"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-elasticsearch-0
  labels:
    app: elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      component: "elasticsearch-0"
  resources:
    requests:
      storage: 10Gi
  volumeName: "elasticsearch-0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    server: 192.168.123.254
    path: "/home/nfsshare/elasticsearch-1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-elasticsearch-1
  labels:
    app: elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      component: "elasticsearch-1"
  resources:
    requests:
      storage: 10Gi
  volumeName: "elasticsearch-1"
