apiVersion: v1
metadata:
  name: werserveerconfig
data:
  REDIS_SLAVE_HOST: redis-cluster
  REDIS_MASTER_HOST: redis-master
  KUBERNETES_SERVICE_HOST: any string here
  KUBERNETES_SERVICE_PORT: any thing here
  ELASTICSEARCH_HOSTS: http://elasticsearch.default.svc.cluster.local:9200
kind: ConfigMap
---
apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  type: ClusterIP
  ports:
    - port: 8085
      targetPort: 8085
      protocol: TCP
      name: http
  selector:
    app: webserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver

spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      name: webserver
      labels:
        app: webserver
        task: final
    spec:
      containers:
        - image: quay.io/myafk/interactive:stable
          name: webserver
          command: ["interactive", "ingress"]
          env:
            - name: REDIS_SLAVE_HOST
              valueFrom:
                configMapKeyRef:
                  name: werserveerconfig
                  key: REDIS_SLAVE_HOST
            - name: REDIS_MASTER_HOST
              valueFrom:
                configMapKeyRef:
                  name: werserveerconfig
                  key: REDIS_MASTER_HOST
            - name: KUBERNETES_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: werserveerconfig
                  key: KUBERNETES_SERVICE_HOST
            - name: KUBERNETES_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: werserveerconfig
                  key: KUBERNETES_SERVICE_PORT
            - name: ELASTICSEARCH_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: werserveerconfig
                  key: ELASTICSEARCH_HOSTS
          ports:
            - containerPort: 8085