apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  type: ClusterIP
  ports:
    - port: 5601
      targetPort: 5601
      protocol: TCP
      name: http
  selector:
    app: kibana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana

spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      name: kibana
      labels:
        app: kibana
        task: final
        kibana: cluster
    spec:
      containers:
        - image: docker.elastic.co/kibana/kibana:7.1.1
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch:9200
            - name: SERVER_NAME
              value: kibana-logging
            - name: SERVER_BASEPATH
              value: /api/v1/namespaces/kube-system/services/kibana-logging/proxy
            - name: SERVER_REWRITEBASEPATH
              value: "false"
          #            - name: ELASTICSEARCH_HOSTS
          #              value: http://elasticsearch:9200
          #              valueFrom:
          #                configMapKeyRef:
          #                  name: kibanaconfig
          #                  key: ELASTICSEARCH_HOSTS
          name: kibana
          ports:
            - containerPort: 5601