# ConfigMap
apiVersion: v1
metadata:
  name: kibanaconfig
data:
  ELASTICSEARCH_HOSTS: "http://elasticsearch.default.svc.cluster.local:9200"
  SERVER_NAME: "kibana-logging"
  SERVER_BASEPATH: "/api/v1/namespaces/kube-system/services/kibana-logging/proxy"
  SERVER_REWRITEBASEPATH: "false"
kind: ConfigMap
# ClusterIP service for kibana
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  type: ClusterIP
  ports:
    - port: 5601
      targetPort: 5601
      protocol: TCP
      name: http
  selector:
    app: kibana
# Deployment kibana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana

spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      name: kibana
      labels:
        app: kibana
        task: final
        kibana: cluster
    spec:
      containers:
        - image: docker.elastic.co/kibana/kibana:7.1.1
          envFrom:
            - configMapRef:
              name: kibanaconfig
          name: kibana
          ports:
            - containerPort: 5601