# ConfigMap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: es-common
data:
  discovery.seed_hosts: "elasticsearch-0,elasticsearch-1"
  cluster.name: "docker-cluster"
  bootstrapmemory.lock: "false"
  cluster.initial_master_nodes: "elasticsearch-0,elasticsearch-1"
# ClusterIP Service elasticsearch-0
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  type: None
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
      name: http
    - port: 9300
      targetPort: 9300
      protocol: TCP
      name: inter-node
  selector:
    app: elasticsearch

# StatefulSet elasticsearch
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch

spec:
  replicas: 2
  serviceName: elasticsearch
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      name: elasticsearch
      labels:
        app: elasticsearch
        task: final
        es: cluster
    spec:
      containers:
        - image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
          envFrom:
            - configMapRef:
                name: es-common
          name: elasticsearch
          ports:
            - containerPort: 9200
              name: rest
              protocol: TCP

            - containerPort: 9300
              name: inter-node
              protocol: TCP

