apiVersion: v1
kind: Service
metadata:
  name: web-server
  namespace: nginx-ingress
spec:
  type: NodePort
  ports:
    - port: 88
      targetPort: 80
      nodePort: 31609
  selector:
    app: nginx-ingress