apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    tier: backend
data:
  config : |
    server {
      index index.php index.html;
      error_log  /var/log/nginx/error.log;
      access_log /var/log/nginx/access.log;
      root /code;

      location / {
          try_files $uri $uri/ /index.php?$query_string;
      }

      location ~ \.php$ {
          try_files $uri =404;
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass php:9000;
          fastcgi_index index.php;
          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_param PATH_INFO $fastcgi_path_info;
        }
    }

---
apiVersion: v1
kind: Service
metadata:
  name: php
  labels:
    tier: backend
spec:
  selector:
    app: php
    tier: backend
  ports:
    - protocol: TCP
      port: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    tier: backend
spec:
  selector:
    app: nginx
    tier: backend
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: code
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    server: 192.168.123.254
    path: "/home/nfsshare/phpcode"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code
  labels:
    app: backend
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      component: "backend"
  resources:
    requests:
      storage: 1Gi
  volumeName: "code"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
      tier: backend
  template:
    metadata:
      labels:
        app: php
        tier: backend
    spec:
      volumes:
        - name: code
          persistentVolumeClaim:
            claimName: code
      containers:
        - name: php
          image: php:7-fpm
          volumeMounts:
            - name: code
              mountPath: /code
#      initContainers:
#        - name: install
#          image: busybox
#          volumeMounts:
#            - name: code
#              mountPath: /code
#          command:
#            - wget
#            - "-O"
#            - "/code/index.php"
#            - https://raw.githubusercontent.com/do-community/php-kubernetes/master/index.php
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      tier: backend
  template:
    metadata:
      labels:
        app: nginx
        tier: backend
    spec:
      volumes:
        - name: code
          persistentVolumeClaim:
            claimName: code
        - name: config
          configMap:
            name: nginx-config
            items:
              - key: config
                path: site.conf
      containers:
        - name: nginx
          image: nginx:1.7.9
          ports:
            - containerPort: 80
          volumeMounts:
            - name: code
              mountPath: /code
            - name: config
              mountPath: /etc/nginx/conf.d
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: phpapp
  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /$2
#    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: monitoring.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: nginx
              servicePort: 80